CREATE TABLE raw_tracks (
    id TEXT,
    name TEXT,
    popularity INTEGER,
    duration_ms INTEGER,
    explicit BOOLEAN,
    artists TEXT,
    id_artists TEXT,
    release_date TEXT,
    danceability FLOAT,
    energy FLOAT,
    key INTEGER,
    loudness FLOAT,
    mode INTEGER,
    speechiness FLOAT,
    acousticness FLOAT,
    instrumentalness FLOAT,
    liveness FLOAT,
    valence FLOAT,
    tempo FLOAT,
    time_signature INTEGER,
    year INTEGER,
    decade TEXT,
    tempo_class TEXT,
    mood_cluster TEXT
);
